### PR TITLE
Delete .php-cs-fixer.cache

### PR DESCRIPTION
**Pull request by Endermanbugzjfc**

### CODE REVIEW

**Comment by ghost** [comment]
> _ No description provided. _

you say yuo dont have github account?????
https://discord.com/channels/373199722573201408/373214753147060235/987829495534850108
BRUH............

**Review by ghost — COMMENTED** [review]
why delete fie

**Comment by Endermanbugzjfc** [comment]
> > _ No description provided. _
> 
> you say yuo dont have github account????? https://discord.com/channels/373199722573201408/373214753147060235/987829495534850108 BRUH............

https://discord.com/channels/373199722573201408/373214753147060235/986200563546980352
> It got hacked

**Comment by Endermanbugzjfc** [comment]
> why delete fie

Sofe said he accidentally staged it.

**Review by SOF3 — CHANGES_REQUESTED** [review]
also add to .gitignore pls

**Review by SOF3 — APPROVED** [review]

**Pull request merged**
